export interface SkillSet {
  name: string;
  weight: number;
  experienceYears: string | number;
  star?: boolean;
  tags?: string[];
}

export const skillSetArr: SkillSet[] = [
  { weight: 1, name: "Java", experienceYears: "5+", star: true, tags: ["language", "program", "development"] },
  { weight: 1, name: "PHP", experienceYears: "5+", star: true, tags: ["website", "language", "program", "development"] },
  { weight: 1, name: "HTML", experienceYears: "5+", star: true, tags: ["html5", "5", "website"] },
  { weight: 1, name: "Javascript", experienceYears: "5+", star: true, tags: ["website", "language", "program", "development"] },
  { weight: 2, name: "SVG", experienceYears: 5, star: true, tags: ["XML"] },
  { weight: 3, name: "CSS", experienceYears: "5+", star: true, tags: ["website"] },
  { weight: 2, name: "SASS", experienceYears: "5+", star: true, tags: ["website", "css"] },
  { weight: 4, name: "LESS", experienceYears: 1, tags: ["website", "css"] },
  { weight: 2, name: "Agile Development", experienceYears: 4, tags: ["methodology"] },
  { weight: 4, name: "Objective C", experienceYears: 2, tags: ["language", "program", "development"] },
  { weight: 3, name: "Swift", experienceYears: 1, tags: ["language", "program", "development"] },
  { weight: 3, name: "C", experienceYears: 2, tags: ["game", "language", "program", "development"] },
  { weight: 3, name: "C++", experienceYears: 1, tags: ["language", "program", "development"] },
  { weight: 3, name: "Perl", experienceYears: 1, tags: ["scripting", "language", "program", "development"] },
  { weight: 3, name: "SQL (MySql)", experienceYears: "5+", star: true, tags: ["db", "database"]},
  { weight: 4, name: "SQL (Oracle)", experienceYears: 1, tags: ["db", "database"]},
  { weight: 4, name: "SQL (PostgreSQL)", experienceYears: 1, tags: ["db", "database"]},
  { weight: 4, name: "MongoDB", experienceYears: 1, tags: ["db", "database"]},
  { weight: 5, name: "OpenGl", experienceYears: 1, tags: ["graphics", "game", "library"] },
  { weight: 4, name: "Ajax", experienceYears: "5+", tags: ["website"] },
  { weight: 2, name: "XML", experienceYears: "5+" },
  { weight: 3, name: "XSLT", experienceYears: 2, tags: ["XML"] },
  { weight: 2, name: "jQuery", experienceYears: 5, star: true, tags: ["Javascript", "library"] },
  { weight: 3, name: "Dojo", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 3, name: "React", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 5, name: "Flux", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 4, name: "Vuex", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 3, name: "RxJS", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 3, name: "AngularJS", experienceYears: 3, tags: ["Javascript", "library"] },
  { weight: 3, name: "Angular", experienceYears: 3, tags: ["Javascript", "library"] },
  { weight: 3, name: "Underscore", experienceYears: 3, tags: ["Javascript", "library"] },
  { weight: 4, name: "Lodash", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 2, name: "npm", experienceYears: 3, tags: ["Javascript", "module", "manager", "package"] },
  { weight: 4, name: "bower", experienceYears: 1, tags: ["Javascript", "module", "manager", "package"] },
  { weight: 4, name: "Eclipse", experienceYears: 4, tags: ["development", "environment"] },
  { weight: 4, name: "Xcode", experienceYears: "5+", tags: ["development", "environment"] },
  { weight: 4, name: "Visual Studio Code", experienceYears: 2, tags: ["development", "environment"] },
  { weight: 5, name: "CVS", experienceYears: 3, tags: ["version", "control"] },
  { weight: 4, name: "GIT", experienceYears: "5+", tags: ["version", "control"] },
  { weight: 3, name: "Subversion", experienceYears: 4, star: true, tags: ["version", "control"] },
  { weight: 4, name: "Ant", experienceYears: 4, tags: ["build", "Java"] },
  { weight: 3, name: "Maven", experienceYears: 2, tags: ["build"] },
  { weight: 3, name: "Gradle", experienceYears: 1, tags: ["build"] },
  { weight: 3, name: "Gulp", experienceYears: 3, tags: ["build"] },
  { weight: 3, name: "NPM", experienceYears: 3, tags: ["build", "Javascript"] },
  { weight: 6, name: "LAMP Administration", experienceYears: 5, tags: ["linux", "apache", "MySql", "PHP"] },
  { weight: 5, name: "Drupal", experienceYears: 2, tags:["content", "management", "platform"] },
  { weight: 6, name: "Moodle", experienceYears: 1, tags:["content", "management", "platform"] },
  { weight: 2, name: "Linux (Ubuntu, Gentoo)", experienceYears: 5, star: true, tags: ["OS", "Operating", "System"] },
  { weight: 2, name: "Mac OS X", experienceYears: 5, star: true, tags: ["OS", "Operating", "System"] },
  { weight: 2, name: "Windows", experienceYears: 4, tags: ["OS", "Operating", "System"] },
  { weight: 6, name: "Test Driven Development", experienceYears: 4, tags: ["methodology"] },
  { weight: 6, name: "Bugzilla", experienceYears: 3, tags: ["defect", "bug", "story"] },
  { weight: 6, name: "Jira", experienceYears: 4, tags: ["defect", "bug", "story"] },
  { weight: 6, name: "Rally", experienceYears: 3, tags: ["defect", "bug", "story", "website", "agile", "methodology"] },
  { weight: 6, name: "UML", experienceYears: 1, tags: ["development", "methodology", "modeling"] },
  { weight: 6, name: "Bash", experienceYears: 2, tags: ["development", "scripting", "shell"] },
  { weight: 6, name: "Memcached", experienceYears: 1, tags: ["cache", "scale", "website"] },
  { weight: 6, name: "Hibernate", experienceYears: 1, tags: ["java", "library"] },
  { weight: 6, name: "Spring", experienceYears: 1, tags: ["java", "library"] },
  { weight: 6, name: "Apache Tomcat", experienceYears: 1, tags: ["java", "website"] },
  { weight: 6, name: "Glassfish", experienceYears: 1, tags: ["java", "website"] },
  { weight: 2, name: "TypeScript", experienceYears: 3, star: true, tags: ["language", "website", "development", "program"] },
  { weight: 2, name: "Python", experienceYears: 2, tags: ["language", "website", "development", "program"] },
  { weight: 3, name: "Docker", experienceYears: 1, tags: ["management", "website", "environment", "development"] },
  { weight: 6, name: "Kubernetes", experienceYears: 1, tags: ["management", "website", "environment", "development"] },
  { weight: 5, name: "Stash", experienceYears: 2, tags: ["version", "control", "development", "git"] },
  { weight: 3, name: "i18n", experienceYears: 4, tags: ["development"] },
  { weight: 6, name: "TSLint", experienceYears: 2, tags: ["development"] },
  { weight: 2, name: "AWS", experienceYears: 1, tags: ["amazon", "development", "management", "services"] },
  { weight: 6, name: "Socket.io", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 3, name: "Microservices", experienceYears: 2, tags: ["environment"] },
  { weight: 6, name: "OpenAPI", experienceYears: 1, tags: ["rest", "api", "swagger"] },
  { weight: 4, name: "Vue.js", experienceYears: 1, tags: ["Javascript", "library"] },
  { weight: 4, name: "Material Design", experienceYears: 2, tags: ["Javascript", "Design", "library"] },
  { weight: 4, name: "Bootstrap", experienceYears: 4, tags: ["Javascript", "Design", "library"] }
];

const synomyns = {
  'js': 'javascript',
  'ts': 'typescript'
};
